baseURL = "https://rets-etsmtl-ca.vercel.app/"
title = "RETS"
theme = "educenter-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "educenter" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


#################### default parameters ################################
[params]
logoHeader = "images/logoHeader.png"
logoFooter = "images/logoFooter.png"
logoGoogle = "images/google-calendar.png"
logoOutlook = "images/outlook-calendar.png"
# Meta data
description = "This is meta description"
author = "Themefisher"
# contact info
address = "9567 Turner Trace Apt. BC C3G8A4"
mobile = "+211234565523"
email = "info@educenter.com"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io // veuillez créer votre compte
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = true

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyC9w8AbEHCIJFhrqh1X_WY0xsXuh0Q46Kg&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png" # marker size 37*55 px

# cookies
[params.cookies]
enable = true
expire_days = 2
  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "#"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2021 a hugo theme by [Themefisher](https://themefisher.com/hugo-themes/)"



################### English navigation ####################

# main menu
[[Languages.en.menu.main]]
name = "About"
url = "about/"
weight = 1

[[Languages.en.menu.main]]
name = "Events"
url = "events/"
weight = 2

[[Languages.en.menu.main]]
name = "Partners"
url = "partners/"
weight = 3

[[Languages.en.menu.main]]
name = "Podcast"
url = "podcast/"
weight = 4
  
[[Languages.en.menu.main]]
name = "Contact"
url = "contact/"
weight = 5


# footer menu

[[Languages.en.menu.footer]]
name = "notice"
url = "notice/"

[[Languages.en.menu.footer]]
name = "event"
url = "event/"

[[Languages.en.menu.footer]]
name = "scholarship"
url = "scholarship/"

[[Languages.en.menu.footer]]
name = "research"
url = "research/"



################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"
# copyright
copyright = "Copyright &copy; 2021 a hugo theme by [Themefisher](https://themefisher.com/hugo-themes/)"



################### French navigation ####################

# main menu
[[Languages.fr.menu.main]]
name = "À propos"
url = "about/"
weight = 1

[[Languages.fr.menu.main]]
name = "Événements"
url = "events/"
weight = 2

[[Languages.fr.menu.main]]
name = "Partenaires"
url = "partners/"
weight = 3
  
[[Languages.fr.menu.main]]
name = "Podcast"
url = "podcast/"
weight = 4
  
[[Languages.fr.menu.main]]
name = "Contact"
url = "contact/"
weight = 5


# footer menu

[[Languages.fr.menu.footer]]
name = "notice"
url = "notice/"

[[Languages.fr.menu.footer]]
name = "event"
url = "event/"

[[Languages.fr.menu.footer]]
name = "scholarship"
url = "scholarship/"

[[Languages.fr.menu.footer]]
name = "research"
url = "research/"
